# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
  # - osx
julia:
  - 1
  - 1.2
  - nightly

matrix:
  allow_failures:
  - julia: nightly

addons:
  apt:
    packages:
      - at-spi2-core
      - libgtk-3-dev
      - xauth
      - xvfb
      
dist: trusty

sudo: required

services:
  - docker
  
before_install:
  - echo "**** pulling Docker image"
  - docker pull tkpapp/texlive-julia-minimal
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then pwd ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then ./test/install_wkhtmltoimage.sh ; fi

notifications:
  email: true

script:
  - echo "**** running Docker"
  - docker run --env-file travis_docker_env.list -t -a STDOUT -a STDIN -a STDERR -v $PWD:/mnt tkpapp/texlive-julia-minimal travis_docker_test_script.sh $TRAVIS_JULIA_VERSION
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - if [[ `uname` = "Linux" ]]; then TESTCMD="xvfb-run julia"; else TESTCMD="julia"; fi
  - $TESTCMD -e 'using Pkg; Pkg.build(); Pkg.test(coverage=true)'
